In [14]:
import pandas as pd
import samplics
import numpy as np
from samplics.estimation import TaylorEstimator, ReplicateEstimator
from samplics.utils import PopParam, SinglePSUEst

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_sas(r'data/LLCP2022.XPT')

In [4]:
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,COLGSEX1,NUMADULT,LANDSEX1,NUMMEN,NUMWOMEN,RESPSLCT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX1,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,SLEPTIM1,LASTDEN4,RMVTETH4,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,ALCDAY4,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,PNEUVAC4,TETANUS1,HIVTST7,HIVTSTD3,HIVRISK5,COVIDPOS,COVIDSMP,COVIDPRM,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,TOLDCFS,HAVECFS,WORKCFS,IMFVPLA3,HPVADVC4,HPVADSHT,SHINGLE2,COVIDVA1,COVACGET,COVIDNU1,COVIDINT,COVIDFS1,COVIDSE1,COPDCOGH,COPDFLEM,COPDBRTH,COPDBTST,COPDSMOK,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,PSATEST1,PSATIME1,PCPSARS2,PSASUGST,PCSTALK1,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,LSATISFY,EMTSUPRT,SDHISOLT,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,SDHSTRE1,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,ASBIALCH,ASBIDRNK,ASBIBING,ASBIADVC,ASBIRDUC,FIREARM5,GUNLOAD,LOADULK2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,HADSEX,PFPPRVN4,TYPCNTR9,BRTHCNT4,WHEREGET,NOBCUSE8,BCPREFER,RRCLASS3,RRCOGNT2,RRTREAT,RRATWRK2,RRHCARE4,RRPHYSM2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE2,_CPRACE2,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPLN,_HCVU652,_TOTINDA,_EXTETH3,_ALTETH3,_DENVST3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_PRACE2,_MRACE2,_HISPANC,_RACE1,_RACEG22,_RACEGR4,_RACEPR1,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_RFMAM22,_MAM5023,_HADCOLN,_CLNSCP1,_HADSIGM,_SGMSCP1,_SGMS101,_RFBLDS5,_STOLDN1,_VIRCOL1,_SBONTI1,_CRCREC2,_SMOKER3,_RFSMOK3,_CURECI2,_YRSSMOK,_PACKDAY,_PACKYRS,_YRSQUIT,_SMOKGRP,_LCSREC,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,1.0,b'02032022',b'02',b'03',b'2022',1100.0,b'2022000001',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,2.0,8.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,80.0,1.0,6.0,1.0,1.0,1.0,2.0,2.0,7.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,2.0,1.0,3.0,2.0,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,4.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,1.0,92021.0,2.0,3.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,487.612985,1.0,1.0,1.0,9.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,4.0,9.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,1.0,b'02042022',b'02',b'04',b'2022',1100.0,b'2022000002',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,3.0,2.0,2.0,8.0,2.0,6.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,3.0,NaN,3.0,4.0,1.0,1.0,2.0,1.0,2.0,2.0,88.0,5.0,NaN,150.0,503.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,4.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,5.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,432.100273,1.0,1.0,1.0,1.0,9.0,2.0,9.0,9.0,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,63.0,160.0,6804.0,2657.0,3.0,2.0,1.0,2.0,3.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0
2,1.0,1.0,b'02022022',b'02',b'02',b'2022',1100.0,b'2022000003',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,5.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,6.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,10.0,NaN,140.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,888.0,NaN,NaN,NaN,2.0,NaN,2.0,7.0,2.0,NaN,2.0,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,2.0,11011.0,37.418416,1.0,37.418416,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,406.959258,366.743194,1.0,2.0,2.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,8.0,1.0,56.0,5.0,62.0,157.0,6350.0,2561.0,3.0,2.0,1.0,4.0,6.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0
3,1.0,1.0,b'02032022',b'02',b'03',b'2022',1100.0,b'2022000004',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,3.0,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,88.0,88.0,NaN,99.0,1.0,2.0,1.0,1.0,7.0,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,77.0,2.0,140.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,7.0,2.0,1.0,1.0,3.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,1.0,17.0,999.0,2.0,1.0,2.0,NaN,888.0,NaN,NaN,NaN,1.0,102021.0,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,3.0,112.255248,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,1220.877775,1681.791487,1.0,1.0,1.0,9.0,9.0,1.0,9.0,9.0,9.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,14.0,3.0,73.0,6.0,65.0,165.0,6350.0,2330.0,2.0,1.0,1.0,2.0,9.0,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,56.0,0.1,6.0,NaN,3.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,9.0,9.0,2.0
4,1.0,1.0,b'02022022',b'02',b'02',b'2022',1100.0,b'2022000005',2.022000e+09,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,88.0,88.0,7.0,2.0,2.0,1.0,1.0,9.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,5.0,1.0,2.0,NaN,2.0,2.0,5.0,88.0,5.0,2.0,119.0,502.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,1.0,NaN,NaN,NaN,1.0,2.0,NaN,203.0,2.0,88.0,2.0,2.0,NaN,1.0,4.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,37.418416,2.0,74.836832,1.0,9.0,NaN,NaN,NaN,NaN,1.0,0.520383,813.918517,2111.206286,2.0,2.0,1.0,1.0,1.0,1.0,9.0,NaN,9.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,43.0,3.0,62.0,157.0,5398.0,2177.0,2.0,1.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0,1.000000e+01,1.0,1.400000e+02,1.0,NaN,NaN,2.0

In [ ]:
# South Dakota 46
sd = df[df['_STATE']==46]
sd.shape
sd_saved = sd.copy()

In [124]:
def recode_smoker(df):
    df.loc[df['_RFSMOK3'] == 1, 'CURRENTUSE'] = 0
    df.loc[df['_RFSMOK3'] == 2, 'CURRENTUSE'] = 1
    df['_RFSMOK3'] = df['CURRENTUSE'].replace(9, np.nan)
    return df

sd = sd_saved.copy()
sd['Test'] = 1
sd['CURRENTUSE'] = np.nan
sd = recode_smoker(sd)

In [125]:
stratified_proportion = TaylorEstimator(PopParam.prop, alpha=0.05)

In [126]:
stratified_proportion.estimate(
    y=sd["_RFSMOK3"],
    samp_weight=sd["_LLCPWT"],
    stratum=sd["_STSTR"],
    psu=sd["_PSU"],
    domain=sd['Test'],
    remove_nan=True)

In [127]:
result = stratified_proportion.to_dataframe()
result

,_param,_domain,_level,_estimate,_stderror,_lci,_uci,_cv
0,PopParam.prop,1,0.0,0.859841,0.012199,0.834178,0.882093,0.014188
1,PopParam.prop,1,1.0,0.140159,0.012199,0.117907,0.165822,0.087040

In [ ]:
# samplics - LCI: 11.7907  UCI: 16.5822
# SAS -      LCI: 11.6244  UCI: 16.4075
# R -        LCI: 11.62477 UCI: 16.40706

In [128]:
stratified_proportion

SAMPLICS - Estimation of Proportion

Number of strata: 32
Number of psus: 7240
Degree of freedom: 7208

 DOMAIN  LEVEL  PROPORTION       SE      LCI      UCI       CV
      1    0.0    0.859841 0.012199 0.834178 0.882093 0.014188
      1    1.0    0.140159 0.012199 0.117907 0.165822 0.087040

In [19]:
nd[nd['_RACE'] == 1].shape

(5016, 342)

In [16]:
# df['_STRWT']

In [66]:
for i in df.columns:
    print(i)

_STATE
FMONTH
IDATE
IMONTH
IDAY
IYEAR
DISPCODE
SEQNO
_PSU
CTELENM1
PVTRESD1
COLGHOUS
STATERE1
CELPHONE
LADULT1
COLGSEX
NUMADULT
LANDSEX
NUMMEN
NUMWOMEN
RESPSLCT
SAFETIME
CTELNUM1
CELLFON5
CADULT1
CELLSEX
PVTRESD3
CCLGHOUS
CSTATE1
LANDLINE
HHADULT
SEXVAR
GENHLTH
PHYSHLTH
MENTHLTH
POORHLTH
HLTHPLN1
PERSDOC2
MEDCOST
CHECKUP1
BPHIGH4
BPMEDS
CHOLCHK2
TOLDHI2
CHOLMED2
CVDINFR4
CVDCRHD4
CVDSTRK3
ASTHMA3
ASTHNOW
CHCSCNCR
CHCOCNCR
CHCCOPD2
ADDEPEV3
CHCKDNY2
DIABETE4
DIABAGE3
HAVARTH4
ARTHEXER
ARTHEDU
LMTJOIN3
ARTHDIS2
JOINPAI2
MARITAL
EDUCA
RENTHOM1
NUMHHOL3
NUMPHON3
CPDEMO1B
VETERAN3
EMPLOY1
CHILDREN
INCOME2
WEIGHT2
HEIGHT3
PREGNANT
DEAF
BLIND
DECIDE
DIFFWALK
DIFFDRES
DIFFALON
SMOKE100
SMOKDAY2
STOPSMK2
LASTSMK2
USENOW3
ALCDAY5
AVEDRNK3
DRNK3GE5
MAXDRNKS
EXERANY2
EXRACT11
EXEROFT1
EXERHMM1
EXRACT21
EXEROFT2
EXERHMM2
STRENGTH
FRUIT2
FRUITJU2
FVGREEN1
FRENCHF1
POTATOE1
VEGETAB2
FLUSHOT7
FLSHTMY3
TETANUS1
PNEUVAC4
HIVTST7
HIVTSTD3
HIVRISK5
PDIABTST
PREDIAB1
INSULIN1
BLDSUGAR
FEETCHK3
DOCTDIAB
CHKHEMO3
FEETCHK
EYEEXAM1
DIABEYE
DIABEDU
TOLDCFS
HAVECFS
WORKCFS
TOLDHEPC
TRETHEPC
PRIRHEPC
HAVEHEPC
HAVEHEPB
MEDSHEPB
HPVADVC3
HPVADSHT
IMFVPLA1
SHINGLE2
LCSFIRST
LCSLAST
LCSNUMCG
LCSCTSCN
HADMAM
HOWLONG
HADPAP2
LASTPAP2
HPVTEST
HPLSTTST
HADHYST2
PCPSAAD3
PCPSADI1
PCPSARE1
PSATEST1
PSATIME
PCPSARS1
PCPSADE1
PCDMDEC1
BLDSTOOL
LSTBLDS3
HADSIGM3
HADSGCO1
LASTSIG3
CNCRDIFF
CNCRAGE
CNCRTYP1
CSRVTRT3
CSRVDOC1
CSRVSUM
CSRVRTRN
CSRVINST
CSRVINSR
CSRVDEIN
CSRVCLIN
CSRVPAIN
CSRVCTL2
HLTHCVR1
ASPIRIN
HOMBPCHK
HOMRGCHK
WHEREBP
SHAREBP
WTCHSALT
DRADVISE
INDORTAN
NUMBURN3
SUNPRTCT
WKDAYOUT
WKENDOUT
CIMEMLOS
CDHOUSE
CDASSIST
CDHELP
CDSOCIAL
CDDISCUS
CAREGIV1
CRGVREL3
CRGVLNG1
CRGVHRS1
CRGVPRB3
CRGVALZD
CRGVPER1
CRGVHOU1
CRGVEXPT
ACEDEPRS
ACEDRINK
ACEDRUGS
ACEPRISN
ACEDIVRC
ACEPUNCH
ACEHURT1
ACESWEAR
ACETOUCH
ACETTHEM
ACEHVSEX
PFPPRVN3
TYPCNTR8
NOBCUSE7
ASBIALCH
ASBIDRNK
ASBIBING
ASBIADVC
ASBIRDUC
MARIJAN1
USEMRJN2
RSNMRJN1
FOODSTMP
BIRTHSEX
SOMALE
SOFEMALE
TRNSGNDR
RCSGENDR
RCSRLTN2
CASTHDX2
CASTHNO2
QSTVER
QSTLANG
_METSTAT
_URBSTAT
MSCODE
_STSTR
_STRWT
_RAWRAKE
_WT2RAKE
_IMPRACE
_CHISPNC
_CRACE1
_CPRACE
_CLLCPWT
_DUALUSE
_DUALCOR
_LLCPWT2
_LLCPWT
_RFHLTH
_PHYS14D
_MENT14D
_HCVU651
_RFHYPE5
_CHOLCH2
_RFCHOL2
_MICHD
_LTASTH1
_CASTHM1
_ASTHMS1
_DRDXAR2
_LMTACT2
_LMTWRK2
_PRACE1
_MRACE1
_HISPANC
_RACE
_RACEG21
_RACEGR3
_RACE_G1
_SEX
_AGEG5YR
_AGE65YR
_AGE80
_AGE_G
HTIN4
HTM4
WTKG3
_BMI5
_BMI5CAT
_RFBMI5
_CHLDCNT
_EDUCAG
_INCOMG
_SMOKER3
_RFSMOK3
DRNKANY5
DROCDY3_
_RFBING5
_DRNKWK1
_RFDRHV7
_TOTINDA
METVL11_
METVL21_
MAXVO21_
FC601_
ACTIN12_
ACTIN22_
PADUR1_
PADUR2_
PAFREQ1_
PAFREQ2_
_MINAC11
_MINAC21
STRFREQ_
PAMISS2_
PAMIN12_
PAMIN22_
PA2MIN_
PAVIG12_
PAVIG22_
PA2VIGM_
_PACAT2
_PAINDX2
_PA150R3
_PA300R3
_PA30022
_PASTRNG
_PAREC2
_PASTAE2
FTJUDA2_
FRUTDA2_
GRENDA1_
FRNCHDA_
POTADA1_
VEGEDA2_
_MISFRT1
_MISVEG1
_FRTRES1
_VEGRES1
_FRUTSU1
_VEGESU1
_FRTLT1A
_VEGLT1A
_FRT16A
_VEG23A
_FRUITE1
_VEGETE1
_FLSHOT7
_PNEUMO3
_AIDTST4

In [ ]:
cot_mean_str = TaylorEstimator("mean")

cot_mean_str.estimate(
    y=df["LBXCOT"],
    samp_weight=df["WTMEC2YR"],
    stratum=df["SDMVSTRA"],
    psu=df["SDMVPSU"],
    remove_nan=True)

In [ ]:
    # if max_value != None:
    #     weighted_df = weighted_df[weighted_df['_level'] <= max_value]
        
    # var_prop = TaylorEstimator("mean")
    
    # if domain == None:
    #     var_prop.estimate(y=unweighted_df[variable],
    #                       samp_weight=unweighted_df[weight],
    #                       stratum=unweighted_df["SDMVSTRA"],
    #                       psu=unweighted_df["SDMVPSU"],
    #                       remove_nan=True)
    # else:
    #     df_all[domain] = df_all[domain].astype('str')
    #     var_prop.estimate(y=unweighted_df[variable],
    #                       samp_weight=unweighted_df[variable],
    #                       stratum=unweighted_df["SDMVSTRA"],
    #                       psu=unweighted_df["SDMVPSU"],
    #                       domain=unweighted_df[domain],
    #                       remove_nan=True)

    # df = var_prop.to_dataframe()

In [72]:
# Testing Prportions:

cot_mean_prop = TaylorEstimator("proportion")

cot_mean_prop.estimate(
    y=df[var],
    samp_weight=df["WTMEC2YR"],
    stratum=df["SDMVSTRA"],
    psu=df["SDMVPSU"],
    remove_nan=True)

In [73]:
result = cot_mean_prop.to_dataframe()
result

         _param  _level  _estimate  _stderror      _lci      _uci       _cv
0    proportion    0.20   0.234551   0.018758  0.196948  0.276859  0.079974
1    proportion    0.28   0.012489   0.002120  0.008690  0.017918  0.169784
2    proportion    0.29   0.011799   0.001810  0.008503  0.016352  0.153441
3    proportion    0.30   0.013374   0.002519  0.008944  0.019955  0.188331
4    proportion    0.31   0.014026   0.002322  0.009849  0.019941  0.165528
5    proportion    0.32   0.011497   0.001353  0.008944  0.014768  0.117646
6    proportion    0.33   0.013442   0.001746  0.010187  0.017719  0.129873
7    proportion    0.34   0.009593   0.001159  0.007413  0.012406  0.120792
8    proportion    0.35   0.010825   0.001660  0.007803  0.015001  0.153359
9    proportion    0.36   0.008234   0.001355  0.005796  0.011686  0.164526
10   proportion    0.37   0.010535   0.002570  0.006256  0.017689  0.243924
11   proportion    0.38   0.010608   0.002747  0.006100  0.018387  0.258975
12   proportion    0.39   0.009084   0.001734  0.006044  0.013633  0.190874
13   proportion    0.40   0.010582   0.001599  0.007664  0.014595  0.151140
14   proportion    0.41   0.006810   0.001230  0.004632  0.010003  0.180660
15   proportion    0.42   0.013935   0.003372  0.008306  0.023288  0.242000
16   proportion    0.43   0.008590   0.001613  0.005753  0.012808  0.187808
17   proportion    0.44   0.010744   0.001756  0.007580  0.015209  0.163394
18   proportion    0.45   0.006863   0.001402  0.004438  0.010599  0.204267
19   proportion    0.46   0.005489   0.001255  0.003370  0.008929  0.228609
20   proportion    0.47   0.006709   0.002170  0.003363  0.013339  0.323398
21   proportion    0.48   0.005342   0.001447  0.002996  0.009507  0.270932
22   proportion    0.49   0.005497   0.001312  0.003303  0.009134  0.238672
23   proportion    0.50   0.007389   0.001631  0.004613  0.011815  0.220678
24   proportion    0.51   0.008855   0.001940  0.005547  0.014109  0.219069
25   proportion    0.52   0.006319   0.001344  0.004013  0.009936  0.212733
26   proportion    0.53   0.007625   0.001335  0.005248  0.011067  0.175076
27   proportion    0.54   0.004452   0.001281  0.002409  0.008213  0.287838
28   proportion    0.55   0.005037   0.001120  0.003134  0.008085  0.222333
29   proportion    0.56   0.006549   0.001815  0.003625  0.011804  0.277083
30   proportion    0.57   0.008991   0.001935  0.005678  0.014210  0.215258
31   proportion    0.58   0.005941   0.001067  0.004050  0.008708  0.179591
32   proportion    0.59   0.008400   0.001359  0.005947  0.011853  0.161816
33   proportion    0.60   0.004144   0.000802  0.002743  0.006256  0.193469
34   proportion    0.61   0.006291   0.001736  0.003491  0.011311  0.275868
35   proportion    0.62   0.006762   0.002094  0.003491  0.013059  0.309672
36   proportion    0.63   0.005520   0.001687  0.002874  0.010574  0.305676
37   proportion    0.64   0.008033   0.002461  0.004175  0.015398  0.306317
38   proportion    0.65   0.008373   0.002200  0.004777  0.014637  0.262793
39   proportion    0.66   0.004207   0.000885  0.002686  0.006583  0.210315
40   proportion    0.67   0.005680   0.001147  0.003692  0.008729  0.201886
41   proportion    0.68   0.004090   0.001314  0.002061  0.008101  0.321248
42   proportion    0.69   0.006958   0.001391  0.004541  0.010648  0.199943
43   proportion    0.70   0.004105   0.000699  0.002855  0.005899  0.170245
44   proportion    0.71   0.004578   0.001216  0.002597  0.008058  0.265656
45   proportion    0.72   0.005013   0.001737  0.002393  0.010474  0.346519
46   proportion    0.73   0.008209   0.002167  0.004671  0.014385  0.263954
47   proportion    0.74   0.006308   0.000993  0.004509  0.008818  0.157380
48   proportion    0.75   0.002825   0.001022  0.001306  0.006100  0.361741
49   proportion    0.76   0.002718   0.000765  0.001492  0.004948  0.281246
50   proportion    0.77   0.003323   0.001210  0.001529  0.007209  0.363956
51   proportion    0.78   0.004551   0.000888  0.003001  0.006897  0.195192
52   proportion    0.79   0.004339   0.001369  0.002213  0.008490  0.315488
53   proportion    0.80   0.004540   0.001171  0.002619  0.007859  0.257840
54   proportion    0.81   0.003120   0.000851  0.001743  0.005578  0.272866
55   proportion    0.82   0.003756   0.001227  0.001870  0.007528  0.326743
56   proportion    0.83   0.004213   0.001470  0.002001  0.008848  0.348821
57   proportion    0.84   0.006129   0.001452  0.003697  0.010144  0.236822
58   proportion    0.85   0.003398   0.000998  0.001816  0.006350  0.293781
59   proportion    0.86   0.005377   0.001020  0.003587  0.008052  0.189715
60   proportion    0.87   0.004484   0.001038  0.002737  0.007340  0.231486
61   proportion    0.88   0.003466   0.000835  0.002074  0.005788  0.240751
62   proportion    0.89   0.004256   0.000754  0.002916  0.006207  0.177195
63   proportion    0.90   0.004217   0.001240  0.002251  0.007884  0.294086
64   proportion    0.91   0.004289   0.001366  0.002174  0.008445  0.318457
65   proportion    0.92   0.003719   0.001301  0.001764  0.007828  0.349725
66   proportion    0.93   0.003283   0.000755  0.002011  0.005357  0.229879
67   proportion    0.94   0.003142   0.001094  0.001495  0.006592  0.348213
68   proportion    0.95   0.002322   0.000876  0.001038  0.005186  0.377385
69   proportion    0.96   0.003717   0.001220  0.001845  0.007473  0.328269
70   proportion    0.97   0.002806   0.000616  0.001757  0.004479  0.219539
71   proportion    0.98   0.002864   0.001446  0.000976  0.008379  0.504755
72   proportion    0.99   0.003900   0.001253  0.001966  0.007725  0.321161
73   proportion    1.00   0.002805   0.001091  0.001224  0.006417  0.388862
74   proportion    1.01   0.000906   0.000366  0.000383  0.002143  0.403880
75   proportion    1.02   0.003640   0.001249  0.001750  0.007555  0.343244
76   proportion    1.03   0.003289   0.000960  0.001765  0.006122  0.291806
77   proportion    1.04   0.003838   0.001095  0.002089  0.007044  0.285245
78   proportion    1.05   0.001221   0.000570  0.000451  0.003302  0.467017
79   proportion    1.06   0.003606   0.001197  0.001776  0.007308  0.331980
80   proportion    1.07   0.003416   0.001208  0.001606  0.007249  0.353626
81   proportion    1.08   0.003103   0.000689  0.001932  0.004980  0.222134
82   proportion    1.09   0.001087   0.000563  0.000360  0.003278  0.518310
83   proportion    1.10   0.003477   0.001019  0.001861  0.006488  0.293056
84   proportion    1.11   0.000464   0.000261  0.000140  0.001536  0.561818
85   proportion    1.12   0.002596   0.000789  0.001358  0.004959  0.303932
86   proportion    1.13   0.001797   0.000578  0.000904  0.003567  0.321982
87   proportion    1.14   0.003139   0.001098  0.001489  0.006606  0.349628
88   proportion    1.15   0.001749   0.000546  0.000898  0.003403  0.312450
89   proportion    1.16   0.003044   0.000700  0.001864  0.004966  0.229828
90   proportion    1.17   0.002598   0.001154  0.001008  0.006684  0.444072
91   proportion    1.18   0.001983   0.000825  0.000817  0.004806  0.415729
92   proportion    1.19   0.001794   0.000827  0.000671  0.004787  0.460921
93   proportion    1.20   0.001266   0.000339  0.000715  0.002240  0.267756
94   proportion    1.21   0.003309   0.001104  0.001625  0.006730  0.333536
95   proportion    1.22   0.000660   0.000311  0.000242  0.001804  0.471573
96   proportion    1.23   0.001297   0.000701  0.000410  0.004099  0.540376
97   proportion    1.24   0.004154   0.001699  0.001735  0.009910  0.408918
98   proportion    1.25   0.001450   0.000626  0.000578  0.003634  0.431420
99   proportion    1.26   0.001534   0.000702  0.000578  0.004062  0.457477
100  proportion    1.27   0.002827   0.001079  0.001253  0.006368  0.381494
101  proportion    1.28   0.000520   0.000399  0.000101  0.002667  0.767913
102  proportion    1.29   0.001803   0.000785  0.000713  0.004555  0.435199
103  proportion    1.30   0.001403   0.000481  0.000675  0.002910  0.342727
104  proportion    1.31   0.001676   0.000793  0.000611  0.004590  0.473229
105  proportion    1.32   0.002092   0.000843  0.000886  0.004932  0.402975
106  proportion    1.33   0.001142   0.000632  0.000351  0.003711  0.553383
107  proportion    1.34   0.002484   0.001103  0.000964  0.006388  0.443833
108  proportion    1.35   0.000609   0.000274  0.000234  0.001587  0.449605
109  proportion    1.36   0.002009   0.000885  0.000785  0.005132  0.440577
110  proportion    1.37   0.001114   0.000562  0.000380  0.003260  0.504142
111  proportion    1.38   0.001744   0.000623  0.000815  0.003731  0.357044
112  proportion    1.39   0.002583   0.001086  0.001053  0.006320  0.420536
113  proportion    1.40   0.001996   0.001012  0.000677  0.005873  0.507075
114  proportion    1.41   0.001198   0.000457  0.000531  0.002702  0.381671
115  proportion    1.42   0.002529   0.000796  0.001292  0.004945  0.314858
116  proportion    1.43   0.000291   0.000200  0.000067  0.001260  0.687540
117  proportion    1.44   0.001496   0.000470  0.000766  0.002921  0.314110
118  proportion    1.45   0.000740   0.000441  0.000208  0.002635  0.596189
119  proportion    1.46   0.001164   0.000274  0.000704  0.001921  0.235381
120  proportion    1.47   0.001651   0.000801  0.000587  0.004635  0.484890
121  proportion    1.48   0.003668   0.001123  0.001909  0.007036  0.306140
122  proportion    1.49   0.000402   0.000208  0.000134  0.001211  0.517120
123  proportion    1.51   0.001125   0.000727  0.000283  0.004456  0.646815
124  proportion    1.52   0.002227   0.001022  0.000837  0.005913  0.458851
125  proportion    1.53   0.000129   0.000129  0.000015  0.001092  1.001821
126  proportion    1.54   0.001975   0.000651  0.000978  0.003984  0.329433
127  proportion    1.55   0.000513   0.000305  0.000145  0.001820  0.594001
128  proportion    1.56   0.002056   0.001217  0.000582  0.007240  0.591745
129  proportion    1.57   0.001323   0.000511  0.000580  0.003013  0.386553
130  proportion    1.58   0.002064   0.000700  0.001001  0.004251  0.339279
131  proportion    1.59   0.002263   0.001104  0.000799  0.006393  0.487966
132  proportion    1.60   0.000604   0.000303  0.000208  0.001758  0.501061
133  proportion    1.61   0.001498   0.000648  0.000595  0.003762  0.432524
134  proportion    1.62   0.001899   0.000753  0.000815  0.004418  0.396688
135  proportion    1.63   0.002421   0.000902  0.001093  0.005352  0.372674
136  proportion    1.64   0.001353   0.000801  0.000383  0.004771  0.592038
137  proportion    1.65   0.000848   0.000314  0.000385  0.001867  0.370210
138  proportion    1.66   0.002040   0.000877  0.000816  0.005093  0.429721
139  proportion    1.67   0.002182   0.000912  0.000895  0.005311  0.417934
140  proportion    1.68   0.001169   0.000644  0.000361  0.003777  0.550871
141  proportion    1.69   0.001182   0.000532  0.000452  0.003082  0.450206
142  proportion    1.70   0.001261   0.000381  0.000663  0.002399  0.301848
143  proportion    1.71   0.001367   0.000750  0.000424  0.004394  0.548575
144  proportion    1.72   0.001816   0.000914  0.000621  0.005301  0.503223
145  proportion    1.73   0.000489   0.000318  0.000122  0.001956  0.650764
146  proportion    1.74   0.000401   0.000185  0.000150  0.001074  0.461914
147  proportion    1.75   0.001805   0.000864  0.000651  0.004999  0.478474
148  proportion    1.76   0.001217   0.000595  0.000429  0.003445  0.488722
149  proportion    1.77   0.001747   0.000971  0.000534  0.005698  0.555452
150  proportion    1.78   0.000475   0.000250  0.000155  0.001458  0.526509
151  proportion    1.79   0.001595   0.001024  0.000405  0.006255  0.642317
152  proportion    1.80   0.001015   0.000571  0.000306  0.003363  0.562459
153  proportion    1.81   0.000237   0.000177  0.000048  0.001166  0.747952
154  proportion    1.82   0.001349   0.000568  0.000550  0.003305  0.420902
155  proportion    1.83   0.001158   0.000555  0.000417  0.003215  0.479295
156  proportion    1.84   0.001277   0.000721  0.000383  0.004247  0.564455
157  proportion    1.85   0.001032   0.000609  0.000293  0.003627  0.590356
158  proportion    1.86   0.001020   0.000597  0.000292  0.003549  0.585764
159  proportion    1.87   0.002129   0.001186  0.000648  0.006966  0.557328
160  proportion    1.88   0.000955   0.000702  0.000199  0.004569  0.735195
161  proportion    1.89   0.000852   0.000636  0.000173  0.004170  0.746262
162  proportion    1.90   0.000188   0.000137  0.000040  0.000891  0.730371
163  proportion    1.91   0.000904   0.000543  0.000251  0.003250  0.601055
164  proportion    1.92   0.000849   0.000343  0.000358  0.002009  0.404417
165  proportion    1.93   0.002222   0.001143  0.000742  0.006637  0.514274
166  proportion    1.94   0.002445   0.001047  0.000980  0.006082  0.428306
167  proportion    1.95   0.001134   0.000713  0.000297  0.004321  0.628383
168  proportion    1.96   0.001185   0.000474  0.000505  0.002778  0.399979
169  proportion    1.97   0.000575   0.000305  0.000186  0.001780  0.530327
170  proportion    1.98   0.000241   0.000245  0.000027  0.002109  1.018708
171  proportion    1.99   0.000113   0.000080  0.000025  0.000512  0.710846
172  proportion    2.00   0.000835   0.000496  0.000235  0.002959  0.593878
173  proportion    2.01   0.001094   0.000669  0.000297  0.004022  0.611479
174  proportion    2.02   0.001321   0.000716  0.000415  0.004190  0.542288
175  proportion    2.03   0.002478   0.000890  0.001152  0.005322  0.359150
176  proportion    2.04   0.000180   0.000132  0.000037  0.000861  0.735697
177  proportion    2.05   0.000518   0.000452  0.000081  0.003318  0.872556
178  proportion    2.06   0.000517   0.000446  0.000082  0.003252  0.864044
179  proportion    2.07   0.000096   0.000095  0.000011  0.000797  0.994583
180  proportion    2.08   0.000449   0.000270  0.000125  0.001614  0.600723
181  proportion    2.10   0.001125   0.000689  0.000304  0.004147  0.612968
182  proportion    2.11   0.001454   0.000919  0.000378  0.005580  0.632060
183  proportion    2.12   0.000263   0.000169  0.000066  0.001038  0.644963
184  proportion    2.13   0.001119   0.001024  0.000159  0.007830  0.915002
185  proportion    2.14   0.000854   0.000623  0.000180  0.004034  0.729198
186  proportion    2.15   0.000218   0.000131  0.000060  0.000784  0.601086
187  proportion    2.16   0.001016   0.000591  0.000293  0.003509  0.582250
188  proportion    2.17   0.001333   0.000928  0.000302  0.005861  0.696024
189  proportion    2.18   0.000666   0.000686  0.000074  0.005962  1.030374
190  proportion    2.19   0.001634   0.000838  0.000547  0.004871  0.512967
191  proportion    2.20   0.001430   0.000730  0.000481  0.004238  0.510437
192  proportion    2.21   0.000480   0.000479  0.000057  0.004016  0.998041
193  proportion    2.23   0.000127   0.000127  0.000015  0.001078  1.004518
194  proportion    2.24   0.000800   0.000540  0.000190  0.003371  0.675221
195  proportion    2.25   0.000119   0.000115  0.000015  0.000940  0.970950
196  proportion    2.26   0.000648   0.000273  0.000264  0.001590  0.421238
197  proportion    2.27   0.000467   0.000332  0.000102  0.002126  0.712040
198  proportion    2.28   0.000882   0.000632  0.000191  0.004051  0.716391
199  proportion    2.29   0.000392   0.000309  0.000073  0.002098  0.787332
200  proportion    2.30   0.000115   0.000116  0.000013  0.000986  1.007984
201  proportion    2.31   0.000165   0.000166  0.000019  0.001408  1.005171
202  proportion    2.32   0.001103   0.000756  0.000255  0.004747  0.685914
203  proportion    2.33   0.000579   0.000579  0.000069  0.004855  0.998766
204  proportion    2.34   0.000287   0.000202  0.000064  0.001289  0.705548
205  proportion    2.35   0.000564   0.000337  0.000157  0.002018  0.598400
206  proportion    2.36   0.001168   0.000644  0.000361  0.003777  0.551037
207  proportion    2.37   0.000172   0.000178  0.000019  0.001556  1.034821
208  proportion    2.38   0.000688   0.000388  0.000207  0.002286  0.564137
209  proportion    2.39   0.001174   0.000830  0.000260  0.005289  0.707376
210  proportion    2.40   0.000343   0.000219  0.000088  0.001332  0.636260
211  proportion    2.41   0.000454   0.000292  0.000115  0.001786  0.642538
212  proportion    2.42   0.000294   0.000230  0.000056  0.001555  0.781753
213  proportion    2.43   0.000109   0.000109  0.000013  0.000921  1.001821
214  proportion    2.44   0.000080   0.000080  0.000009  0.000680  1.005891
215  proportion    2.45   0.000819   0.000331  0.000345  0.001938  0.404615
216  proportion    2.47   0.000555   0.000359  0.000139  0.002205  0.647873
217  proportion    2.48   0.000224   0.000217  0.000028  0.001776  0.972744
218  proportion    2.49   0.000278   0.000195  0.000063  0.001236  0.699940
219  proportion    2.50   0.000904   0.000213  0.000547  0.001494  0.235925
220  proportion    2.51   0.000669   0.000409  0.000182  0.002460  0.611147
221  proportion    2.52   0.001392   0.000837  0.000386  0.005003  0.600958
222  proportion    2.53   0.000119   0.000120  0.000014  0.001028  1.012471
223  proportion    2.54   0.002278   0.001086  0.000824  0.006279  0.476504
224  proportion    2.55   0.001021   0.000402  0.000441  0.002363  0.394023
225  proportion    2.56   0.000366   0.000235  0.000093  0.001439  0.642345
226  proportion    2.57   0.000053   0.000053  0.000006  0.000443  0.998041
227  proportion    2.58   0.000394   0.000287  0.000083  0.001864  0.729806
228  proportion    2.59   0.000409   0.000266  0.000103  0.001632  0.649375
229  proportion    2.60   0.000673   0.000679  0.000078  0.005752  1.008230
230  proportion    2.61   0.001539   0.001042  0.000363  0.006498  0.676989
231  proportion    2.62   0.000206   0.000028  0.000153  0.000276  0.137784
232  proportion    2.63   0.000634   0.000403  0.000163  0.002459  0.636609
233  proportion    2.64   0.000134   0.000132  0.000017  0.001089  0.982429
234  proportion    2.65   0.000568   0.000415  0.000120  0.002689  0.730117
235  proportion    2.66   0.000134   0.000136  0.000015  0.001158  1.012471
236  proportion    2.67   0.000049   0.000050  0.000006  0.000422  1.007984
237  proportion    2.69   0.000674   0.000571  0.000111  0.004095  0.847704
238  proportion    2.70   0.000516   0.000275  0.000165  0.001607  0.533645
239  proportion    2.71   0.000037   0.000037  0.000004  0.000316  1.007984
240  proportion    2.72   0.000168   0.000119  0.000037  0.000765  0.711819
241  proportion    2.73   0.000146   0.000148  0.000017  0.001260  1.012471
242  proportion    2.74   0.000088   0.000089  0.000010  0.000748  1.002127
243  proportion    2.75   0.000510   0.000513  0.000060  0.004336  1.005891
244  proportion    2.76   0.000504   0.000401  0.000092  0.002747  0.796325
245  proportion    2.78   0.000244   0.000181  0.000050  0.001185  0.741556
246  proportion    2.79   0.001131   0.000620  0.000351  0.003637  0.548637
247  proportion    2.80   0.000163   0.000119  0.000034  0.000772  0.729603
248  proportion    2.81   0.000376   0.000268  0.000082  0.001715  0.712390
249  proportion    2.82   0.000092   0.000091  0.000011  0.000748  0.982429
250  proportion    2.83   0.001271   0.000807  0.000328  0.004910  0.634998
251  proportion    2.85   0.000321   0.000241  0.000065  0.001592  0.751678
252  proportion    2.86   0.000682   0.000463  0.000160  0.002893  0.678769
253  proportion    2.89   0.000089   0.000090  0.000010  0.000767  1.012471
254  proportion    2.90   0.000241   0.000240  0.000029  0.002008  0.995927
255  proportion    2.91   0.001309   0.000830  0.000338  0.005050  0.634372
256  proportion    2.92   0.000404   0.000259  0.000103  0.001583  0.640811
257  proportion    2.93   0.000370   0.000371  0.000044  0.003124  1.002127
258  proportion    2.94   0.001125   0.000769  0.000262  0.004823  0.683725
259  proportion    2.95   0.000323   0.000200  0.000086  0.001212  0.621073
260  proportion    2.96   0.000324   0.000191  0.000092  0.001141  0.590849
261  proportion    2.97   0.000149   0.000149  0.000018  0.001257  1.001821

In [74]:
pd.set_option('display.max_rows', None)
result['cumulative'] = result['_estimate'].cumsum()
result

,_param,_level,_estimate,_stderror,_lci,_uci,_cv,cumulative
0,proportion,0.20,0.234551,0.018758,0.196948,0.276859,0.079974,0.234551
1,proportion,0.28,0.012489,0.002120,0.008690,0.017918,0.169784,0.247040
2,proportion,0.29,0.011799,0.001810,0.008503,0.016352,0.153441,0.258839
3,proportion,0.30,0.013374,0.002519,0.008944,0.019955,0.188331,0.272213
4,proportion,0.31,0.014026,0.002322,0.009849,0.019941,0.165528,0.286240
5,proportion,0.32,0.011497,0.001353,0.008944,0.014768,0.117646,0.297737
6,proportion,0.33,0.013442,0.001746,0.010187,0.017719,0.129873,0.311179
7,proportion,0.34,0.009593,0.001159,0.007413,0.012406,0.120792,0.320772
8,proportion,0.35,0.010825,0.001660,0.007803,0.015001,0.153359,0.331597
9,proportion,0.36,0.008234,0.001355,0.005796,0.011686,0.164526,0.339831
10,proportion,0.37,0.010535,0.002570,0.006256,0.017689,0.243924,0.350367
11,proportion,0.38,0.010608,0.002747,0.006100,0.018387,0.258975,0.360975
12,proportion,0.39,0.009084,0.001734,0.006044,0.013633,0.190874,0.370059
13,proportion,0.40,0.010582,0.001599,0.007664,0.014595,0.151140,0.380641
14,proportion,0.41,0.006810,0.001230,0.004632,0.010003,0.180660,0.387451
15,proportion,0.42,0.013935,0.003372,0.008306,0.023288,0.242000,0.401386
16,proportion,0.43,0.008590,0.001613,0.005753,0.012808,0.187808,0.409976
17,proportion,0.44,0.010744,0.001756,0.007580,0.015209,0.163394,0.420720
18,proportion,0.45,0.006863,0.001402,0.004438,0.010599,0.204267,0.427583
19,proportion,0.46,0.005489,0.001255,0.003370,0.008929,0.228609,0.433072
20,proportion,0.47,0.006709,0.002170,0.003363,0.013339,0.323398,0.439781
21,proportion,0.48,0.005342,0.001447,0.002996,0.009507,0.270932,0.445123
22,proportion,0.49,0.005497,0.001312,0.003303,0.009134,0.238672,0.450620
23,proportion,0.50,0.007389,0.001631,0.004613,0.011815,0.220678,0.458009
24,proportion,0.51,0.008855,0.001940,0.005547,0.014109,0.219069,0.466864
25,proportion,0.52,0.006319,0.001344,0.004013,0.009936,0.212733,0.473183
26,proportion,0.53,0.007625,0.001335,0.005248,0.011067,0.175076,0.480808
27,proportion,0.54,0.004452,0.001281,0.002409,0.008213,0.287838,0.485260
28,proportion,0.55,0.005037,0.001120,0.003134,0.008085,0.222333,0.490297
29,proportion,0.56,0.006549,0.001815,0.003625,0.011804,0.277083,0.496846
30,proportion,0.57,0.008991,0.001935,0.005678,0.014210,0.215258,0.505837
31,proportion,0.58,0.005941,0.001067,0.004050,0.008708,0.179591,0.511778
32,proportion,0.59,0.008400,0.001359,0.005947,0.011853,0.161816,0.520178
33,proportion,0.60,0.004144,0.000802,0.002743,0.006256,0.193469,0.524322
34,proportion,0.61,0.006291,0.001736,0.003491,0.011311,0.275868,0.530614
35,proportion,0.62,0.006762,0.002094,0.003491,0.013059,0.309672,0.537375
36,proportion,0.63,0.005520,0.001687,0.002874,0.010574,0.305676,0.542895
37,proportion,0.64,0.008033,0.002461,0.004175,0.015398,0.306317,0.550928
38,proportion,0.65,0.008373,0.002200,0.004777,0.014637,0.262793,0.559301
39,proportion,0.66,0.004207,0.000885,0.002686,0.006583,0.210315,0.563508
40,proportion,0.67,0.005680,0.001147,0.003692,0.008729,0.201886,0.569188
41,proportion,0.68,0.004090,0.001314,0.002061,0.008101,0.321248,0.573277
42,proportion,0.69,0.006958,0.001391,0.004541,0.010648,0.199943,0.580236
43,proportion,0.70,0.004105,0.000699,0.002855,0.005899,0.170245,0.584340
44,proportion,0.71,0.004578,0.001216,0.002597,0.008058,0.265656,0.588919
45,proportion,0.72,0.005013,0.001737,0.002393,0.010474,0.346519,0.593932
46,proportion,0.73,0.008209,0.002167,0.004671,0.014385,0.263954,0.602140
47,proportion,0.74,0.006308,0.000993,0.004509,0.008818,0.157380,0.608448
48,proportion,0.75,0.002825,0.001022,0.001306,0.006100,0.361741,0.611273
49,proportion,0.76,0.002718,0.000765,0.001492,0.004948,0.281246,0.613991
50,proportion,0.77,0.003323,0.001210,0.001529,0.007209,0.363956,0.617315
51,proportion,0.78,0.004551,0.000888,0.003001,0.006897,0.195192,0.621866
52,proportion,0.79,0.004339,0.001369,0.002213,0.008490,0.315488,0.626205
53,proportion,0.80,0.004540,0.001171,0.002619,0.007859,0.257840,0.630745
54,proportion,0.81,0.003120,0.000851,0.001743,0.005578,0.272866,0.633865
55,proportion,0.82,0.003756,0.001227,0.001870,0.007528,0.326743,0.637621
56,proportion,0.83,0.004213,0.001470,0.002001,0.008848,0.348821,0.641834
57,proportion,0.84,0.006129,0.001452,0.003697,0.010144,0.236822,0.647963
58,proportion,0.85,0.003398,0.000998,0.001816,0.006350,0.293781,0.651361
59,proportion,0.86,0.005377,0.001020,0.003587,0.008052,0.189715,0.656738
60,proportion,0.87,0.004484,0.001038,0.002737,0.007340,0.231486,0.661222
61,proportion,0.88,0.003466,0.000835,0.002074,0.005788,0.240751,0.664688
62,proportion,0.89,0.004256,0.000754,0.002916,0.006207,0.177195,0.668944
63,proportion,0.90,0.004217,0.001240,0.002251,0.007884,0.294086,0.673161
64,proportion,0.91,0.004289,0.001366,0.002174,0.008445,0.318457,0.677450
65,proportion,0.92,0.003719,0.001301,0.001764,0.007828,0.349725,0.681170
66,proportion,0.93,0.003283,0.000755,0.002011,0.005357,0.229879,0.684453
67,proportion,0.94,0.003142,0.001094,0.001495,0.006592,0.348213,0.687595
68,proportion,0.95,0.002322,0.000876,0.001038,0.005186,0.377385,0.689917
69,proportion,0.96,0.003717,0.001220,0.001845,0.007473,0.328269,0.693634
70,proportion,0.97,0.002806,0.000616,0.001757,0.004479,0.219539,0.696440
71,proportion,0.98,0.002864,0.001446,0.000976,0.008379,0.504755,0.699304
72,proportion,0.99,0.003900,0.001253,0.001966,0.007725,0.321161,0.703205
73,proportion,1.00,0.002805,0.001091,0.001224,0.006417,0.388862,0.706009
74,proportion,1.01,0.000906,0.000366,0.000383,0.002143,0.403880,0.706916
75,proportion,1.02,0.003640,0.001249,0.001750,0.007555,0.343244,0.710555
76,proportion,1.03,0.003289,0.000960,0.001765,0.006122,0.291806,0.713845
77,proportion,1.04,0.003838,0.001095,0.002089,0.007044,0.285245,0.717683
78,proportion,1.05,0.001221,0.000570,0.000451,0.003302,0.467017,0.718905
79,proportion,1.06,0.003606,0.001197,0.001776,0.007308,0.331980,0.722510
80,proportion,1.07,0.003416,0.001208,0.001606,0.007249,0.353626,0.725926
81,proportion,1.08,0.003103,0.000689,0.001932,0.004980,0.222134,0.729029
82,proportion,1.09,0.001087,0.000563,0.000360,0.003278,0.518310,0.730116
83,proportion,1.10,0.003477,0.001019,0.001861,0.006488,0.293056,0.733593
84,proportion,1.11,0.000464,0.000261,0.000140,0.001536,0.561818,0.734057
85,proportion,1.12,0.002596,0.000789,0.001358,0.004959,0.303932,0.736654
86,proportion,1.13,0.001797,0.000578,0.000904,0.003567,0.321982,0.738450
87,proportion,1.14,0.003139,0.001098,0.001489,0.006606,0.349628,0.741589
88,proportion,1.15,0.001749,0.000546,0.000898,0.003403,0.312450,0.743338
89,proportion,1.16,0.003044,0.000700,0.001864,0.004966,0.229828,0.746382
90,proportion,1.17,0.002598,0.001154,0.001008,0.006684,0.444072,0.748981
91,proportion,1.18,0.001983,0.000825,0.000817,0.004806,0.415729,0.750964
92,proportion,1.19,0.001794,0.000827,0.000671,0.004787,0.460921,0.752759
93,proportion,1.20,0.001266,0.000339,0.000715,0.002240,0.267756,0.754025
94,proportion,1.21,0.003309,0.001104,0.001625,0.006730,0.333536,0.757334
95,proportion,1.22,0.000660,0.000311,0.000242,0.001804,0.471573,0.757995
96,proportion,1.23,0.001297,0.000701,0.000410,0.004099,0.540376,0.759292
97,proportion,1.24,0.004154,0.001699,0.001735,0.009910,0.408918,0.763446
98,proportion,1.25,0.001450,0.000626,0.000578,0.003634,0.431420,0.764896
99,proportion,1.26,0.001534,0.000702,0.000578,0.004062,0.457477,0.766430
100,proportion,1.27,0.002827,0.001079,0.001253,0.006368,0.381494,0.769257
101,proportion,1.28,0.000520,0.000399,0.000101,0.002667,0.767913,0.769777
102,proportion,1.29,0.001803,0.000785,0.000713,0.004555,0.435199,0.771580
103,proportion,1.30,0.001403,0.000481,0.000675,0.002910,0.342727,0.772983
104,proportion,1.31,0.001676,0.000793,0.000611,0.004590,0.473229,0.774659
105,proportion,1.32,0.002092,0.000843,0.000886,0.004932,0.402975,0.776750
106,proportion,1.33,0.001142,0.000632,0.000351,0.003711,0.553383,0.777893
107,proportion,1.34,0.002484,0.001103,0.000964,0.006388,0.443833,0.780377
108,proportion,1.35,0.000609,0.000274,0.000234,0.001587,0.449605,0.780986
109,proportion,1.36,0.002009,0.000885,0.000785,0.005132,0.440577,0.782995
110,proportion,1.37,0.001114,0.000562,0.000380,0.003260,0.504142,0.784109
111,proportion,1.38,0.001744,0.000623,0.000815,0.003731,0.357044,0.785853
112,proportion,1.39,0.002583,0.001086,0.001053,0.006320,0.420536,0.788436
113,proportion,1.40,0.001996,0.001012,0.000677,0.005873,0.507075,0.790432
114,proportion,1.41,0.001198,0.000457,0.000531,0.002702,0.381671,0.791631
115,proportion,1.42,0.002529,0.000796,0.001292,0.004945,0.314858,0.794160
116,proportion,1.43,0.000291,0.000200,0.000067,0.001260,0.687540,0.794451
117,proportion,1.44,0.001496,0.000470,0.000766,0.002921,0.314110,0.795947
118,proportion,1.45,0.000740,0.000441,0.000208,0.002635,0.596189,0.796687
119,proportion,1.46,0.001164,0.000274,0.000704,0.001921,0.235381,0.797851
120,proportion,1.47,0.001651,0.000801,0.000587,0.004635,0.484890,0.799502
121,proportion,1.48,0.003668,0.001123,0.001909,0.007036,0.306140,0.803169
122,proportion,1.49,0.000402,0.000208,0.000134,0.001211,0.517120,0.803572
123,proportion,1.51,0.001125,0.000727,0.000283,0.004456,0.646815,0.804697
124,proportion,1.52,0.002227,0.001022,0.000837,0.005913,0.458851,0.806923
125,proportion,1.53,0.000129,0.000129,0.000015,0.001092,1.001821,0.807053
126,proportion,1.54,0.001975,0.000651,0.000978,0.003984,0.329433,0.809028
127,proportion,1.55,0.000513,0.000305,0.000145,0.001820,0.594001,0.809542
128,proportion,1.56,0.002056,0.001217,0.000582,0.007240,0.591745,0.811598
129,proportion,1.57,0.001323,0.000511,0.000580,0.003013,0.386553,0.812920
130,proportion,1.58,0.002064,0.000700,0.001001,0.004251,0.339279,0.814984
131,proportion,1.59,0.002263,0.001104,0.000799,0.006393,0.487966,0.817248
132,proportion,1.60,0.000604,0.000303,0.000208,0.001758,0.501061,0.817852
133,proportion,1.61,0.001498,0.000648,0.000595,0.003762,0.432524,0.819350
134,proportion,1.62,0.001899,0.000753,0.000815,0.004418,0.396688,0.821249
135,proportion,1.63,0.002421,0.000902,0.001093,0.005352,0.372674,0.823670
136,proportion,1.64,0.001353,0.000801,0.000383,0.004771,0.592038,0.825023
137,proportion,1.65,0.000848,0.000314,0.000385,0.001867,0.370210,0.825871
138,proportion,1.66,0.002040,0.000877,0.000816,0.005093,0.429721,0.827911
139,proportion,1.67,0.002182,0.000912,0.000895,0.005311,0.417934,0.830093
140,proportion,1.68,0.001169,0.000644,0.000361,0.003777,0.550871,0.831262
141,proportion,1.69,0.001182,0.000532,0.000452,0.003082,0.450206,0.832444
142,proportion,1.70,0.001261,0.000381,0.000663,0.002399,0.301848,0.833705
143,proportion,1.71,0.001367,0.000750,0.000424,0.004394,0.548575,0.835071
144,proportion,1.72,0.001816,0.000914,0.000621,0.005301,0.503223,0.836887
145,proportion,1.73,0.000489,0.000318,0.000122,0.001956,0.650764,0.837376
146,proportion,1.74,0.000401,0.000185,0.000150,0.001074,0.461914,0.837778
147,proportion,1.75,0.001805,0.000864,0.000651,0.004999,0.478474,0.839583
148,proportion,1.76,0.001217,0.000595,0.000429,0.003445,0.488722,0.840800
149,proportion,1.77,0.001747,0.000971,0.000534,0.005698,0.555452,0.842547
150,proportion,1.78,0.000475,0.000250,0.000155,0.001458,0.526509,0.843022
151,proportion,1.79,0.001595,0.001024,0.000405,0.006255,0.642317,0.844617
152,proportion,1.80,0.001015,0.000571,0.000306,0.003363,0.562459,0.845632
153,proportion,1.81,0.000237,0.000177,0.000048,0.001166,0.747952,0.845869
154,proportion,1.82,0.001349,0.000568,0.000550,0.003305,0.420902,0.847217
155,proportion,1.83,0.001158,0.000555,0.000417,0.003215,0.479295,0.848376
156,proportion,1.84,0.001277,0.000721,0.000383,0.004247,0.564455,0.849653
157,proportion,1.85,0.001032,0.000609,0.000293,0.003627,0.590356,0.850685
158,proportion,1.86,0.001020,0.000597,0.000292,0.003549,0.585764,0.851704
159,proportion,1.87,0.002129,0.001186,0.000648,0.006966,0.557328,0.853833
160,proportion,1.88,0.000955,0.000702,0.000199,0.004569,0.735195,0.854788
161,proportion,1.89,0.000852,0.000636,0.000173,0.004170,0.746262,0.855640
162,proportion,1.90,0.000188,0.000137,0.000040,0.000891,0.730371,0.855828
163,proportion,1.91,0.000904,0.000543,0.000251,0.003250,0.601055,0.856732
164,proportion,1.92,0.000849,0.000343,0.000358,0.002009,0.404417,0.857580
165,proportion,1.93,0.002222,0.001143,0.000742,0.006637,0.514274,0.859803
166,proportion,1.94,0.002445,0.001047,0.000980,0.006082,0.428306,0.862247
167,proportion,1.95,0.001134,0.000713,0.000297,0.004321,0.628383,0.863381
168,proportion,1.96,0.001185,0.000474,0.000505,0.002778,0.399979,0.864566
169,proportion,1.97,0.000575,0.000305,0.000186,0.001780,0.530327,0.865141
170,proportion,1.98,0.000241,0.000245,0.000027,0.002109,1.018708,0.865382
171,proportion,1.99,0.000113,0.000080,0.000025,0.000512,0.710846,0.865495
172,proportion,2.00,0.000835,0.000496,0.000235,0.002959,0.593878,0.866330
173,proportion,2.01,0.001094,0.000669,0.000297,0.004022,0.611479,0.867424
174,proportion,2.02,0.001321,0.000716,0.000415,0.004190,0.542288,0.868745
175,proportion,2.03,0.002478,0.000890,0.001152,0.005322,0.359150,0.871222
176,proportion,2.04,0.000180,0.000132,0.000037,0.000861,0.735697,0.871402
177,proportion,2.05,0.000518,0.000452,0.000081,0.003318,0.872556,0.871920
178,proportion,2.06,0.000517,0.000446,0.000082,0.003252,0.864044,0.872436
179,proportion,2.07,0.000096,0.000095,0.000011,0.000797,0.994583,0.872532
180,proportion,2.08,0.000449,0.000270,0.000125,0.001614,0.600723,0.872981
181,proportion,2.10,0.001125,0.000689,0.000304,0.004147,0.612968,0.874105
182,proportion,2.11,0.001454,0.000919,0.000378,0.005580,0.632060,0.875559
183,proportion,2.12,0.000263,0.000169,0.000066,0.001038,0.644963,0.875822
184,proportion,2.13,0.001119,0.001024,0.000159,0.007830,0.915002,0.876940
185,proportion,2.14,0.000854,0.000623,0.000180,0.004034,0.729198,0.877794
186,proportion,2.15,0.000218,0.000131,0.000060,0.000784,0.601086,0.878012
187,proportion,2.16,0.001016,0.000591,0.000293,0.003509,0.582250,0.879028
188,proportion,2.17,0.001333,0.000928,0.000302,0.005861,0.696024,0.880361
189,proportion,2.18,0.000666,0.000686,0.000074,0.005962,1.030374,0.881027
190,proportion,2.19,0.001634,0.000838,0.000547,0.004871,0.512967,0.882661
191,proportion,2.20,0.001430,0.000730,0.000481,0.004238,0.510437,0.884091
192,proportion,2.21,0.000480,0.000479,0.000057,0.004016,0.998041,0.884571
193,proportion,2.23,0.000127,0.000127,0.000015,0.001078,1.004518,0.884697
194,proportion,2.24,0.000800,0.000540,0.000190,0.003371,0.675221,0.885498
195,proportion,2.25,0.000119,0.000115,0.000015,0.000940,0.970950,0.885616
196,proportion,2.26,0.000648,0.000273,0.000264,0.001590,0.421238,0.886264
197,proportion,2.27,0.000467,0.000332,0.000102,0.002126,0.712040,0.886731
198,proportion,2.28,0.000882,0.000632,0.000191,0.004051,0.716391,0.887612
199,proportion,2.29,0.000392,0.000309,0.000073,0.002098,0.787332,0.888005
200,proportion,2.30,0.000115,0.000116,0.000013,0.000986,1.007984,0.888120
201,proportion,2.31,0.000165,0.000166,0.000019,0.001408,1.005171,0.888285
202,proportion,2.32,0.001103,0.000756,0.000255,0.004747,0.685914,0.889388
203,proportion,2.33,0.000579,0.000579,0.000069,0.004855,0.998766,0.889967
204,proportion,2.34,0.000287,0.000202,0.000064,0.001289,0.705548,0.890254
205,proportion,2.35,0.000564,0.000337,0.000157,0.002018,0.598400,0.890818
206,proportion,2.36,0.001168,0.000644,0.000361,0.003777,0.551037,0.891986
207,proportion,2.37,0.000172,0.000178,0.000019,0.001556,1.034821,0.892158
208,proportion,2.38,0.000688,0.000388,0.000207,0.002286,0.564137,0.892845
209,proportion,2.39,0.001174,0.000830,0.000260,0.005289,0.707376,0.894019
210,proportion,2.40,0.000343,0.000219,0.000088,0.001332,0.636260,0.894362
211,proportion,2.41,0.000454,0.000292,0.000115,0.001786,0.642538,0.894817
212,proportion,2.42,0.000294,0.000230,0.000056,0.001555,0.781753,0.895111
213,proportion,2.43,0.000109,0.000109,0.000013,0.000921,1.001821,0.895220
214,proportion,2.44,0.000080,0.000080,0.000009,0.000680,1.005891,0.895299
215,proportion,2.45,0.000819,0.000331,0.000345,0.001938,0.404615,0.896118
216,proportion,2.47,0.000555,0.000359,0.000139,0.002205,0.647873,0.896673
217,proportion,2.48,0.000224,0.000217,0.000028,0.001776,0.972744,0.896896
218,proportion,2.49,0.000278,0.000195,0.000063,0.001236,0.699940,0.897174
219,proportion,2.50,0.000904,0.000213,0.000547,0.001494,0.235925,0.898078
220,proportion,2.51,0.000669,0.000409,0.000182,0.002460,0.611147,0.898747
221,proportion,2.52,0.001392,0.000837,0.000386,0.005003,0.600958,0.900140
222,proportion,2.53,0.000119,0.000120,0.000014,0.001028,1.012471,0.900259
223,proportion,2.54,0.002278,0.001086,0.000824,0.006279,0.476504,0.902537
224,proportion,2.55,0.001021,0.000402,0.000441,0.002363,0.394023,0.903558
225,proportion,2.56,0.000366,0.000235,0.000093,0.001439,0.642345,0.903924
226,proportion,2.57,0.000053,0.000053,0.000006,0.000443,0.998041,0.903977
227,proportion,2.58,0.000394,0.000287,0.000083,0.001864,0.729806,0.904370
228,proportion,2.59,0.000409,0.000266,0.000103,0.001632,0.649375,0.904779
229,proportion,2.60,0.000673,0.000679,0.000078,0.005752,1.008230,0.905453
230,proportion,2.61,0.001539,0.001042,0.000363,0.006498,0.676989,0.906992
231,proportion,2.62,0.000206,0.000028,0.000153,0.000276,0.137784,0.907198
232,proportion,2.63,0.000634,0.000403,0.000163,0.002459,0.636609,0.907831
233,proportion,2.64,0.000134,0.000132,0.000017,0.001089,0.982429,0.907966
234,proportion,2.65,0.000568,0.000415,0.000120,0.002689,0.730117,0.908534
235,proportion,2.66,0.000134,0.000136,0.000015,0.001158,1.012471,0.908668
236,proportion,2.67,0.000049,0.000050,0.000006,0.000422,1.007984,0.908717
237,proportion,2.69,0.000674,0.000571,0.000111,0.004095,0.847704,0.909391
238,proportion,2.70,0.000516,0.000275,0.000165,0.001607,0.533645,0.909906
239,proportion,2.71,0.000037,0.000037,0.000004,0.000316,1.007984,0.909943
240,proportion,2.72,0.000168,0.000119,0.000037,0.000765,0.711819,0.910111
241,proportion,2.73,0.000146,0.000148,0.000017,0.001260,1.012471,0.910257
242,proportion,2.74,0.000088,0.000089,0.000010,0.000748,1.002127,0.910345
243,proportion,2.75,0.000510,0.000513,0.000060,0.004336,1.005891,0.910855
244,proportion,2.76,0.000504,0.000401,0.000092,0.002747,0.796325,0.911358
245,proportion,2.78,0.000244,0.000181,0.000050,0.001185,0.741556,0.911603
246,proportion,2.79,0.001131,0.000620,0.000351,0.003637,0.548637,0.912733
247,proportion,2.80,0.000163,0.000119,0.000034,0.000772,0.729603,0.912896
248,proportion,2.81,0.000376,0.000268,0.000082,0.001715,0.712390,0.913272
249,proportion,2.82,0.000092,0.000091,0.000011,0.000748,0.982429,0.913365
250,proportion,2.83,0.001271,0.000807,0.000328,0.004910,0.634998,0.914636
251,proportion,2.85,0.000321,0.000241,0.000065,0.001592,0.751678,0.914957
252,proportion,2.86,0.000682,0.000463,0.000160,0.002893,0.678769,0.915638
253,proportion,2.89,0.000089,0.000090,0.000010,0.000767,1.012471,0.915727
254,proportion,2.90,0.000241,0.000240,0.000029,0.002008,0.995927,0.915968
255,proportion,2.91,0.001309,0.000830,0.000338,0.005050,0.634372,0.917277
256,proportion,2.92,0.000404,0.000259,0.000103,0.001583,0.640811,0.917681
257,proportion,2.93,0.000370,0.000371,0.000044,0.003124,1.002127,0.918051
258,proportion,2.94,0.001125,0.000769,0.000262,0.004823,0.683725,0.919176
259,proportion,2.95,0.000323,0.000200,0.000086,0.001212,0.621073,0.919499
260,proportion,2.96,0.000324,0.000191,0.000092,0.001141,0.590849,0.919823
261,proportion,2.97,0.000149,0.000149,0.000018,0.001257,1.001821,0.919971
262,proportion,2.98,0.000686,0.000619,0.000100,0.004677,0.901906,0.920657
263,proportion,3.00,0.000567,0.000570,0.000066,0.004815,1.005171,0.921224
264,proportion,3.02,0.000944,0.000638,0.000223,0.003983,0.676420,0.922168
265,proportion,3.03,0.000243,0.000180,0.000050,0.001177,0.740113,0.922411
266,proportion,3.04,0.000351,0.000214,0.000096,0.001284,0.608006,0.922762
267,proportion,3.05,0.000813,0.000375,0.000304,0.002170,0.461117,0.923575
268,proportion,3.06,0.000622,0.000522,0.000104,0.003715,0.839710,0.924197
269,proportion,3.07,0.000569,0.000388,0.000133,0.002427,0.680858,0.924766

In [13]:
def find_percentile(df, percentile):
    target = percentile / 100.0
    return df[df['cumulative'] >= target]['_level'].iloc[0]

# Find the 50th percentile (median)
median_level = find_percentile(result, 50)
print(f'The magnitude at the 50th percentile is: {median_level}')

The magnitude at the 50th percentile is: 0.16

In [14]:
# Compute confidence intervals using Korn and Graubard method
alpha = 0.05
z_score = np.abs(np.percentile(np.random.standard_normal(1000000), [alpha/2, 1 - alpha/2]))

# Get the standard error for the median level
stderr = result[result['_level'] == median_level]['_stderror'].iloc[0]

# Compute the confidence interval for the median
lower_ci = median_level - z_score[1] * stderr
upper_ci = median_level + z_score[1] * stderr

print(f'Confidence interval for the 50th percentile: ({lower_ci}, {upper_ci})')

Confidence interval for the 50th percentile: (0.14156723481006972, 0.1784327651899303)

In [16]:
import scipy.stats as stats
# Calculate the confidence intervals for the proportion
alpha = 0.05
z = stats.norm.ppf(1 - alpha / 2)
# z = np.abs(np.percentile(np.random.standard_normal(1000000), [alpha/2, 1 - alpha/2]))


# Calculate the cumulative sum of the variance
result['cumulative_var'] = (result['_stderror'] ** 2).cumsum()

# Find the standard error for the 50th percentile
std_error_at_percentile = np.sqrt(result[result['cumulative'] >= 0.5]['cumulative_var'].iloc[0])

# Compute the proportion at 50th percentile
proportion = result[result['cumulative'] >= 0.5]['cumulative'].iloc[0]

# Calculate the CI for the proportion
lower_ci_proportion = proportion - z * std_error_at_percentile
upper_ci_proportion = proportion + z * std_error_at_percentile

# Transform back to magnitude (level) using interpolation
lower_ci_level = np.interp(lower_ci_proportion, result['cumulative'], result['_level'])
upper_ci_level = np.interp(upper_ci_proportion, result['cumulative'], result['_level'])

print(f'Confidence interval for the 50th percentile: ({lower_ci_level}, {upper_ci_level})')

Confidence interval for the 50th percentile: (0.1543394632077199, 0.16635747414272717)

In [20]:
def recode_df_domains(df):
    # Map number to Race
    race_mapping = {
        1.0: 'Mexican American',
        2.0: 'Other Hispanic',
        3.0: 'Non-Hispanic White',
        4.0: 'Non-Hispanic Black',
        5.0: 'Other Race - Including Multi-Racial'}
    df['RIDRETH1'] = df['RIDRETH1'].replace(race_mapping)

    # Map number to Gender
    gender_mapping = {
        1.0: 'Male',
        2.0: 'Female'}
    df['RIAGENDR'] = df['RIAGENDR'].replace(gender_mapping)

    # Create Youth Age Groups
    conditions = [
        df['RIDAGEYR'].apply(lambda x: 3 <= x < 6),
        df['RIDAGEYR'].apply(lambda x: 6 <= x < 12),
        df['RIDAGEYR'].apply(lambda x: 12 <= x < 20)]

    choices = [
        'a. Age 03-05 years',
        'b. Age 06-11 years',
        'c. Age 12-19 years']

    df['Youth Age Group'] = np.select(conditions, choices, default='d. Age 20+ years')

    return df

In [60]:
df = recode_df_domains(df)

In [61]:
df.head()

,SEQN,WTSH2YR,LBXBPB,LBDBPBSI,LBDBPBLC,LBXBCD,LBDBCDSI,LBDBCDLC,LBXTHG,LBDTHGSI,LBDTHGLC,LBXBSE,LBDBSESI,LBDBSELC,LBXBMN,LBDBMNSI,LBDBMNLC,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,DMQMILIZ,DMQADFC,DMDBORN4,DMDCITZN,DMDYRSUS,DMDEDUC3,DMDEDUC2,DMDMARTL,RIDEXPRG,SIALANG,SIAPROXY,SIAINTRP,FIALANG,FIAPROXY,FIAINTRP,MIALANG,MIAPROXY,MIAINTRP,AIALANGA,DMDHHSIZ,DMDFMSIZ,DMDHHSZA,DMDHHSZB,DMDHHSZE,DMDHRGND,DMDHRAGE,DMDHRBR4,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR,Youth Age Group
0,73558.0,49123.400015,1.69,0.082,5.397605e-79,0.20,1.78,5.397605e-79,1.21,6.0,5.397605e-79,204.73,2.60,5.397605e-79,8.15,148.33,5.397605e-79,8.0,2.0,Male,54.0,NaN,Non-Hispanic White,3.0,1.0,NaN,2.0,NaN,1.0,1.0,NaN,NaN,3.0,1.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,4.0,5.397605e-79,2.000000e+00,5.397605e-79,1.0,54.0,1.0,3.0,1.0,1.0,23682.057386,24471.769625,1.0,108.0,7.0,7.0,1.78,d. Age 20+ years
1,73559.0,115794.742161,1.45,0.070,5.397605e-79,0.22,1.96,5.397605e-79,1.27,6.3,5.397605e-79,209.64,2.66,5.397605e-79,9.57,174.17,5.397605e-79,8.0,2.0,Male,72.0,NaN,Non-Hispanic White,3.0,2.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,4.0,1.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,5.397605e-79,5.397605e-79,2.000000e+00,1.0,72.0,1.0,4.0,1.0,3.0,57214.803319,57193.285376,1.0,109.0,10.0,10.0,4.51,d. Age 20+ years
2,73560.0,55766.512438,0.37,0.018,5.397605e-79,0.07,0.62,1.000000e+00,0.88,4.4,5.397605e-79,169.82,2.16,5.397605e-79,13.07,237.87,5.397605e-79,8.0,2.0,Male,9.0,NaN,Non-Hispanic White,3.0,1.0,119.0,NaN,NaN,1.0,1.0,NaN,3.0,NaN,NaN,NaN,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,4.0,5.397605e-79,2.000000e+00,5.397605e-79,1.0,33.0,1.0,3.0,1.0,4.0,55201.178592,55766.512438,2.0,109.0,9.0,9.0,2.52,b. Age 06-11 years
3,73562.0,47860.935312,0.91,0.044,5.397605e-79,0.20,1.78,5.397605e-79,1.10,5.5,5.397605e-79,187.63,2.38,5.397605e-79,13.99,254.62,5.397605e-79,8.0,2.0,Male,56.0,NaN,Mexican American,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,NaN,4.0,3.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,5.397605e-79,1.0,56.0,1.0,4.0,3.0,NaN,24978.144602,25344.992359,1.0,111.0,9.0,9.0,4.79,d. Age 20+ years
4,73564.0,125448.894530,1.00,0.048,5.397605e-79,0.37,3.29,5.397605e-79,0.42,2.1,5.397605e-79,195.62,2.48,5.397605e-79,16.80,305.76,5.397605e-79,8.0,2.0,Female,61.0,NaN,Non-Hispanic White,3.0,2.0,NaN,2.0,NaN,1.0,1.0,NaN,NaN,5.0,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.000000e+00,2.0,61.0,1.0,5.0,2.0,NaN,60325.095254,61758.654880,1.0,114.0,10.0,10.0,5.00,d. Age 20+ years

In [70]:
# Testing Prportions with Domains:

cot_mean_prop = TaylorEstimator("proportion")

cot_mean_prop.estimate(
    y=df[var],
    # samp_weight=df["WTMEC2YR"],
    samp_weight=df["WTSH2YR"], # Mercury
    stratum=df["SDMVSTRA"],
    psu=df["SDMVPSU"], 
    domain=df['Youth Age Group'],
    remove_nan=True)

In [71]:
result = cot_mean_prop.to_dataframe()
result

          _param             _domain _level  _estimate  _stderror      _lci  \
0     proportion  a. Age 03-05 years    0.2   0.532383   0.039462  0.448149
1     proportion  a. Age 03-05 years   0.28   0.020375   0.007569  0.009183
2     proportion  a. Age 03-05 years   0.29   0.017274   0.008327  0.006141
3     proportion  a. Age 03-05 years    0.3   0.019030   0.008707  0.007128
4     proportion  a. Age 03-05 years   0.31   0.010139   0.004676  0.003781
5     proportion  a. Age 03-05 years   0.32   0.013650   0.004927  0.006304
6     proportion  a. Age 03-05 years   0.33   0.019245   0.007438  0.008400
7     proportion  a. Age 03-05 years   0.34   0.018130   0.008110  0.006944
8     proportion  a. Age 03-05 years   0.35   0.009524   0.003875  0.003991
9     proportion  a. Age 03-05 years   0.36   0.005978   0.002848  0.002160
10    proportion  a. Age 03-05 years   0.37   0.009137   0.004664  0.003066
11    proportion  a. Age 03-05 years   0.38   0.001337   0.001389  0.000146
12    proportion  a. Age 03-05 years   0.39   0.019202   0.009565  0.006588
13    proportion  a. Age 03-05 years    0.4   0.011944   0.006075  0.004019
14    proportion  a. Age 03-05 years   0.41   0.010315   0.003567  0.004925
15    proportion  a. Age 03-05 years   0.42   0.013842   0.006191  0.005310
16    proportion  a. Age 03-05 years   0.43   0.000830   0.000837  0.000097
17    proportion  a. Age 03-05 years   0.44   0.008299   0.003017  0.003816
18    proportion  a. Age 03-05 years   0.45   0.004407   0.002574  0.001266
19    proportion  a. Age 03-05 years   0.46   0.009050   0.006238  0.002069
20    proportion  a. Age 03-05 years   0.47   0.004797   0.002538  0.001550
21    proportion  a. Age 03-05 years   0.48   0.006406   0.003473  0.002011
22    proportion  a. Age 03-05 years   0.49   0.003709   0.003784  0.000420
23    proportion  a. Age 03-05 years    0.5   0.002937   0.002309  0.000548
24    proportion  a. Age 03-05 years   0.51   0.001709   0.001252  0.000358
25    proportion  a. Age 03-05 years   0.52   0.002055   0.001459  0.000452
26    proportion  a. Age 03-05 years   0.53   0.004827   0.002867  0.001357
27    proportion  a. Age 03-05 years   0.54   0.002451   0.001805  0.000509
28    proportion  a. Age 03-05 years   0.55   0.000000   0.000000  0.000000
29    proportion  a. Age 03-05 years   0.56   0.001045   0.001066  0.000119
30    proportion  a. Age 03-05 years   0.57   0.009715   0.006637  0.002249
31    proportion  a. Age 03-05 years   0.58   0.001003   0.001002  0.000119
32    proportion  a. Age 03-05 years   0.59   0.006423   0.003498  0.002006
33    proportion  a. Age 03-05 years    0.6   0.005447   0.001980  0.002507
34    proportion  a. Age 03-05 years   0.61   0.003076   0.002220  0.000659
35    proportion  a. Age 03-05 years   0.62   0.002804   0.002768  0.000341
36    proportion  a. Age 03-05 years   0.63   0.001449   0.001452  0.000171
37    proportion  a. Age 03-05 years   0.64   0.004580   0.001897  0.001892
38    proportion  a. Age 03-05 years   0.65   0.013381   0.011423  0.002140
39    proportion  a. Age 03-05 years   0.66   0.005238   0.002979  0.001554
40    proportion  a. Age 03-05 years   0.67   0.001600   0.001193  0.000326
41    proportion  a. Age 03-05 years   0.68   0.001454   0.001467  0.000169
42    proportion  a. Age 03-05 years   0.69   0.002026   0.002043  0.000235
43    proportion  a. Age 03-05 years    0.7   0.005583   0.002494  0.002151
44    proportion  a. Age 03-05 years   0.71   0.013796   0.009607  0.003096
45    proportion  a. Age 03-05 years   0.72   0.006273   0.006188  0.000760
46    proportion  a. Age 03-05 years   0.73   0.000738   0.000731  0.000089
47    proportion  a. Age 03-05 years   0.74   0.001750   0.001768  0.000203
48    proportion  a. Age 03-05 years   0.75   0.000000   0.000000  0.000000
49    proportion  a. Age 03-05 years   0.76   0.003212   0.002300  0.000696
50    proportion  a. Age 03-05 years   0.77   0.003302   0.002339  0.000728
51    proportion  a. Age 03-05 years   0.78   0.001474   0.001455  0.000179
52    proportion  a. Age 03-05 years   0.79   0.001161   0.001161  0.000137
53    proportion  a. Age 03-05 years    0.8   0.002679   0.001913  0.000584
54    proportion  a. Age 03-05 years   0.81   0.001430   0.001327  0.000197
55    proportion  a. Age 03-05 years   0.82   0.000000   0.000000  0.000000
56    proportion  a. Age 03-05 years   0.83   0.003742   0.002642  0.000829
57    proportion  a. Age 03-05 years   0.84   0.000000   0.000000  0.000000
58    proportion  a. Age 03-05 years   0.85   0.005369   0.002746  0.001801
59    proportion  a. Age 03-05 years   0.86   0.000000   0.000000  0.000000
60    proportion  a. Age 03-05 years   0.87   0.000000   0.000000  0.000000
61    proportion  a. Age 03-05 years   0.88   0.000000   0.000000  0.000000
62    proportion  a. Age 03-05 years   0.89   0.000000   0.000000  0.000000
63    proportion  a. Age 03-05 years    0.9   0.003164   0.002465  0.000600
64    proportion  a. Age 03-05 years   0.91   0.002648   0.002012  0.000523
65    proportion  a. Age 03-05 years   0.92   0.001336   0.001334  0.000159
66    proportion  a. Age 03-05 years   0.93   0.002198   0.002187  0.000263
67    proportion  a. Age 03-05 years   0.94   0.001267   0.001270  0.000149
68    proportion  a. Age 03-05 years   0.95   0.000000   0.000000  0.000000
69    proportion  a. Age 03-05 years   0.96   0.000000   0.000000  0.000000
70    proportion  a. Age 03-05 years   0.97   0.000000   0.000000  0.000000
71    proportion  a. Age 03-05 years   0.98   0.000000   0.000000  0.000000
72    proportion  a. Age 03-05 years   0.99   0.005594   0.002867  0.001872
73    proportion  a. Age 03-05 years    1.0   0.001223   0.001239  0.000141
74    proportion  a. Age 03-05 years   1.01   0.000000   0.000000  0.000000
75    proportion  a. Age 03-05 years   1.02   0.000000   0.000000  0.000000
76    proportion  a. Age 03-05 years   1.03   0.000000   0.000000  0.000000
77    proportion  a. Age 03-05 years   1.04   0.003553   0.002667  0.000716
78    proportion  a. Age 03-05 years   1.05   0.001374   0.001392  0.000158
79    proportion  a. Age 03-05 years   1.06   0.001952   0.001967  0.000227
80    proportion  a. Age 03-05 years   1.07   0.000000   0.000000  0.000000
81    proportion  a. Age 03-05 years   1.08   0.009284   0.007308  0.001720
82    proportion  a. Age 03-05 years   1.09   0.000000   0.000000  0.000000
83    proportion  a. Age 03-05 years    1.1   0.001467   0.001467  0.000174
84    proportion  a. Age 03-05 years   1.11   0.000931   0.000929  0.000111
85    proportion  a. Age 03-05 years   1.12   0.000000   0.000000  0.000000
86    proportion  a. Age 03-05 years   1.13   0.001488   0.001508  0.000171
87    proportion  a. Age 03-05 years   1.14   0.001706   0.001249  0.000358
88    proportion  a. Age 03-05 years   1.15   0.000755   0.000764  0.000087
89    proportion  a. Age 03-05 years   1.16   0.001855   0.001765  0.000243
90    proportion  a. Age 03-05 years   1.17   0.000000   0.000000  0.000000
91    proportion  a. Age 03-05 years   1.18   0.001020   0.001018  0.000121
92    proportion  a. Age 03-05 years   1.19   0.000000   0.000000  0.000000
93    proportion  a. Age 03-05 years    1.2   0.002060   0.002087  0.000237
94    proportion  a. Age 03-05 years   1.21   0.002334   0.002302  0.000284
95    proportion  a. Age 03-05 years   1.22   0.000000   0.000000  0.000000
96    proportion  a. Age 03-05 years   1.23   0.000000   0.000000  0.000000
97    proportion  a. Age 03-05 years   1.24   0.000000   0.000000  0.000000
98    proportion  a. Age 03-05 years   1.25   0.000963   0.000986  0.000109
99    proportion  a. Age 03-05 years   1.26   0.001485   0.001515  0.000168
100   proportion  a. Age 03-05 years   1.27   0.000000   0.000000  0.000000
101   proportion  a. Age 03-05 years   1.28   0.000000   0.000000  0.000000
102   proportion  a. Age 03-05 years   1.29   0.000000   0.000000  0.000000
103   proportion  a. Age 03-05 years    1.3   0.000000   0.000000  0.000000
104   proportion  a. Age 03-05 years   1.31   0.000000   0.000000  0.000000
105   proportion  a. Age 03-05 years   1.32   0.000000   0.000000  0.000000
106   proportion  a. Age 03-05 years   1.33   0.000000   0.000000  0.000000
107   proportion  a. Age 03-05 years   1.34   0.000000   0.000000  0.000000
108   proportion  a. Age 03-05 years   1.35   0.001364   0.001368  0.000160
109   proportion  a. Age 03-05 years   1.36   0.000000   0.000000  0.000000
110   proportion  a. Age 03-05 years   1.37   0.000000   0.000000  0.000000
111   proportion  a. Age 03-05 years   1.38   0.001172   0.001138  0.000148
112   proportion  a. Age 03-05 years   1.39   0.000000   0.000000  0.000000
113   proportion  a. Age 03-05 years    1.4   0.002850   0.002015  0.000630
114   proportion  a. Age 03-05 years   1.41   0.000000   0.000000  0.000000
115   proportion  a. Age 03-05 years   1.42   0.002193   0.002194  0.000259
116   proportion  a. Age 03-05 years   1.43   0.001240   0.001265  0.000141
117   proportion  a. Age 03-05 years   1.44   0.000000   0.000000  0.000000
118   proportion  a. Age 03-05 years   1.45   0.000000   0.000000  0.000000
119   proportion  a. Age 03-05 years   1.46   0.000000   0.000000  0.000000
120   proportion  a. Age 03-05 years   1.47   0.000000   0.000000  0.000000
121   proportion  a. Age 03-05 years   1.48   0.007930   0.007828  0.000958
122   proportion  a. Age 03-05 years   1.49   0.000000   0.000000  0.000000
123   proportion  a. Age 03-05 years   1.51   0.000000   0.000000  0.000000
124   proportion  a. Age 03-05 years   1.52   0.000000   0.000000  0.000000
125   proportion  a. Age 03-05 years   1.53   0.000000   0.000000  0.000000
126   proportion  a. Age 03-05 years   1.54   0.000000   0.000000  0.000000
127   proportion  a. Age 03-05 years   1.55   0.000000   0.000000  0.000000
128   proportion  a. Age 03-05 years   1.56   0.000000   0.000000  0.000000
129   proportion  a. Age 03-05 years   1.57   0.000000   0.000000  0.000000
130   proportion  a. Age 03-05 years   1.58   0.000000   0.000000  0.000000
131   proportion  a. Age 03-05 years   1.59   0.000000   0.000000  0.000000
132   proportion  a. Age 03-05 years    1.6   0.000000   0.000000  0.000000
133   proportion  a. Age 03-05 years   1.61   0.000000   0.000000  0.000000
134   proportion  a. Age 03-05 years   1.62   0.000000   0.000000  0.000000
135   proportion  a. Age 03-05 years   1.63   0.000000   0.000000  0.000000
136   proportion  a. Age 03-05 years   1.64   0.000000   0.000000  0.000000
137   proportion  a. Age 03-05 years   1.65   0.000000   0.000000  0.000000
138   proportion  a. Age 03-05 years   1.66   0.000000   0.000000  0.000000
139   proportion  a. Age 03-05 years   1.67   0.001890   0.001885  0.000225
140   proportion  a. Age 03-05 years   1.68   0.000000   0.000000  0.000000
141   proportion  a. Age 03-05 years   1.69   0.000000   0.000000  0.000000
142   proportion  a. Age 03-05 years    1.7   0.000000   0.000000  0.000000
143   proportion  a. Age 03-05 years   1.71   0.000000   0.000000  0.000000
144   proportion  a. Age 03-05 years   1.72   0.000000   0.000000  0.000000
145   proportion  a. Age 03-05 years   1.73   0.000000   0.000000  0.000000
146   proportion  a. Age 03-05 years   1.74   0.000000   0.000000  0.000000
147   proportion  a. Age 03-05 years   1.75   0.003047   0.003043  0.000361
148   proportion  a. Age 03-05 years   1.76   0.000000   0.000000  0.000000
149   proportion  a. Age 03-05 years   1.77   0.000000   0.000000  0.000000
150   proportion  a. Age 03-05 years   1.78   0.000000   0.000000  0.000000
151   proportion  a. Age 03-05 years   1.79   0.000000   0.000000  0.000000
152   proportion  a. Age 03-05 years    1.8   0.003258   0.003385  0.000354
153   proportion  a. Age 03-05 years   1.81   0.000000   0.000000  0.000000
154   proportion  a. Age 03-05 years   1.82   0.000000   0.000000  0.000000
155   proportion  a. Age 03-05 years   1.83   0.000000   0.000000  0.000000
156   proportion  a. Age 03-05 years   1.84   0.000000   0.000000  0.000000
157   proportion  a. Age 03-05 years   1.85   0.000904   0.000922  0.000103
158   proportion  a. Age 03-05 years   1.86   0.000000   0.000000  0.000000
159   proportion  a. Age 03-05 years   1.87   0.000000   0.000000  0.000000
160   proportion  a. Age 03-05 years   1.88   0.000000   0.000000  0.000000
161   proportion  a. Age 03-05 years   1.89   0.000000   0.000000  0.000000
162   proportion  a. Age 03-05 years    1.9   0.000000   0.000000  0.000000
163   proportion  a. Age 03-05 years   1.91   0.000000   0.000000  0.000000
164   proportion  a. Age 03-05 years   1.92   0.000000   0.000000  0.000000
165   proportion  a. Age 03-05 years   1.93   0.000000   0.000000  0.000000
166   proportion  a. Age 03-05 years   1.94   0.000000   0.000000  0.000000
167   proportion  a. Age 03-05 years   1.95   0.000000   0.000000  0.000000
168   proportion  a. Age 03-05 years   1.96   0.000000   0.000000  0.000000
169   proportion  a. Age 03-05 years   1.97   0.002010   0.001951  0.000253
170   proportion  a. Age 03-05 years   1.98   0.000000   0.000000  0.000000
171   proportion  a. Age 03-05 years   1.99   0.000000   0.000000  0.000000
172   proportion  a. Age 03-05 years    2.0   0.000000   0.000000  0.000000
173   proportion  a. Age 03-05 years   2.01   0.000000   0.000000  0.000000
174   proportion  a. Age 03-05 years   2.02   0.000000   0.000000  0.000000
175   proportion  a. Age 03-05 years   2.03   0.000000   0.000000  0.000000
176   proportion  a. Age 03-05 years   2.04   0.000000   0.000000  0.000000
177   proportion  a. Age 03-05 years   2.05   0.000000   0.000000  0.000000
178   proportion  a. Age 03-05 years   2.06   0.000000   0.000000  0.000000
179   proportion  a. Age 03-05 years   2.07   0.000000   0.000000  0.000000
180   proportion  a. Age 03-05 years   2.08   0.000000   0.000000  0.000000
181   proportion  a. Age 03-05 years    2.1   0.000000   0.000000  0.000000
182   proportion  a. Age 03-05 years   2.11   0.000000   0.000000  0.000000
183   proportion  a. Age 03-05 years   2.12   0.000000   0.000000  0.000000
184   proportion  a. Age 03-05 years   2.13   0.000000   0.000000  0.000000
185   proportion  a. Age 03-05 years   2.14   0.000000   0.000000  0.000000
186   proportion  a. Age 03-05 years   2.15   0.000000   0.000000  0.000000
187   proportion  a. Age 03-05 years   2.16   0.000000   0.000000  0.000000
188   proportion  a. Age 03-05 years   2.17   0.000000   0.000000  0.000000
189   proportion  a. Age 03-05 years   2.18   0.000000   0.000000  0.000000
190   proportion  a. Age 03-05 years   2.19   0.000000   0.000000  0.000000
191   proportion  a. Age 03-05 years    2.2   0.000000   0.000000  0.000000
192   proportion  a. Age 03-05 years   2.21   0.000000   0.000000  0.000000
193   proportion  a. Age 03-05 years   2.23   0.000000   0.000000  0.000000
194   proportion  a. Age 03-05 years   2.24   0.000000   0.000000  0.000000
195   proportion  a. Age 03-05 years   2.25   0.000000   0.000000  0.000000
196   proportion  a. Age 03-05 years   2.26   0.000000   0.000000  0.000000
197   proportion  a. Age 03-05 years   2.27   0.000000   0.000000  0.000000
198   proportion  a. Age 03-05 years   2.28   0.000000   0.000000  0.000000
199   proportion  a. Age 03-05 years   2.29   0.000000   0.000000  0.000000
200   proportion  a. Age 03-05 years    2.3   0.000000   0.000000  0.000000
201   proportion  a. Age 03-05 years   2.31   0.000000   0.000000  0.000000
202   proportion  a. Age 03-05 years   2.32   0.000000   0.000000  0.000000
203   proportion  a. Age 03-05 years   2.33   0.000000   0.000000  0.000000
204   proportion  a. Age 03-05 years   2.34   0.000000   0.000000  0.000000
205   proportion  a. Age 03-05 years   2.35   0.000000   0.000000  0.000000
206   proportion  a. Age 03-05 years   2.36   0.000000   0.000000  0.000000
207   proportion  a. Age 03-05 years   2.37   0.000000   0.000000  0.000000
208   proportion  a. Age 03-05 years   2.38   0.000000   0.000000  0.000000
209   proportion  a. Age 03-05 years   2.39   0.000000   0.000000  0.000000
210   proportion  a. Age 03-05 years    2.4   0.000000   0.000000  0.000000
211   proportion  a. Age 03-05 years   2.41   0.000000   0.000000  0.000000
212   proportion  a. Age 03-05 years   2.42   0.000000   0.000000  0.000000
213   proportion  a. Age 03-05 years   2.43   0.000000   0.000000  0.000000
214   proportion  a. Age 03-05 years   2.44   0.000000   0.000000  0.000000
215   proportion  a. Age 03-05 years   2.45   0.000000   0.000000  0.000000
216   proportion  a. Age 03-05 years   2.47   0.000000   0.000000  0.000000
217   proportion  a. Age 03-05 years   2.48   0.000000   0.000000  0.000000
218   proportion  a. Age 03-05 years   2.49   0.000000   0.000000  0.000000
219   proportion  a. Age 03-05 years    2.5   0.000000   0.000000  0.000000
220   proportion  a. Age 03-05 years   2.51   0.000000   0.000000  0.000000
221   proportion  a. Age 03-05 years   2.52   0.000000   0.000000  0.000000
222   proportion  a. Age 03-05 years   2.53   0.000000   0.000000  0.000000
223   proportion  a. Age 03-05 years   2.54   0.000000   0.000000  0.000000
224   proportion  a. Age 03-05 years   2.55   0.000000   0.000000  0.000000
225   proportion  a. Age 03-05 years   2.56   0.000000   0.000000  0.000000
226   proportion  a. Age 03-05 years   2.57   0.000983   0.000985  0.000116
227   proportion  a. Age 03-05 years   2.58   0.000000   0.000000  0.000000
228   proportion  a. Age 03-05 years   2.59   0.001003   0.001001  0.000119
229   proportion  a. Age 03-05 years    2.6   0.000000   0.000000  0.000000
230   proportion  a. Age 03-05 years   2.61   0.000000   0.000000  0.000000
231   proportion  a. Age 03-05 years   2.62   0.000000   0.000000  0.000000
232   proportion  a. Age 03-05 years   2.63   0.000000   0.000000  0.000000
233   proportion  a. Age 03-05 years   2.64   0.000000   0.000000  0.000000
234   proportion  a. Age 03-05 years   2.65   0.000000   0.000000  0.000000
235   proportion  a. Age 03-05 years   2.66   0.000000   0.000000  0.000000
236   proportion  a. Age 03-05 years   2.67   0.000915   0.000913  0.000109
237   proportion  a. Age 03-05 years   2.69   0.000000   0.000000  0.000000
238   proportion  a. Age 03-05 years    2.7   0.000000   0.000000  0.000000
239   proportion  a. Age 03-05 years   2.71   0.000686   0.000684  0.000082
240   proportion  a. Age 03-05 years   2.72   0.000000   0.000000  0.000000
241   proportion  a. Age 03-05 years   2.73   0.000000   0.000000  0.000000
242   proportion  a. Age 03-05 years   2.74   0.000000   0.000000  0.000000
243   proportion  a. Age 03-05 years   2.75   0.000000   0.000000  0.000000
244   proportion  a. Age 03-05 years   2.76   0.000000   0.000000  0.000000
245   proportion  a. Age 03-05 years   2.78   0.000000   0.000000  0.000000
246   proportion  a. Age 03-05 years   2.79   0.000000   0.000000  0.000000
247   proportion  a. Age 03-05 years    2.8   0.000000   0.000000  0.000000
248   proportion  a. Age 03-05 years   2.81   0.000000   0.000000  0.000000
249   proportion  a. Age 03-05 years   2.82   0.000000   0.000000  0.000000
250   proportion  a. Age 03-05 years   2.83   0.000643   0.000651  0.000074
251   proportion  a. Age 03-05 years   2.85   0.000000   0.000000  0.000000
252   proportion  a. Age 03-05 years   2.86   0.000000   0.000000  0.000000
253   proportion  a. Age 03-05 years   2.89   0.000000   0.000000  0.000000
254   proportion  a. Age 03-05 years    2.9   0.000000   0.000000  0.000000
255   proportion  a. Age 03-05 years   2.91   0.000000   0.000000  0.000000
256   proportion  a. Age 03-05 years   2.92   0.001391   0.001388  0.000165
257   proportion  a. Age 03-05 years   2.93   0.006880   0.006680  0.000861
258   proportion  a. Age 03-05 years   2.94   0.000000   0.000000  0.000000
259   proportion  a. Age 03-05 years   2.95   0.000000   0.000000  0.000000
260   proportion  a. Age 03-05 years   2.96   0.000000   0.000000  0.000000
261   proportion  a. Age 03-05 years   2.97   0.000000   0.000000  0.000000